### ISSUE TITLE
Upgrades TODO

### ISSUE THREAD

**Issue by suppergerrie2** [suppergerrie2/ModJam5#16]
- [x] Storage upgrade for hauler drones
- [x] Speed upgrade for all drones
- [x] Farm size upgrade for crop farm drones
- [ ] Farm size upgrade for tree farm drones
- [ ] Other drone range upgrades
- [ ] Damage upgrades for fighting drones (Archer and melee)
- [ ] Swimming upgrade? (Not sure if they should be able to swim without upgrades)

Comment here if you have an idea!

**Comment by Haze33E** [comment]
- Equipping drones with different tool and weapon types (wood, stone, and iron)

- Equipping drones with enchanted tools and weapons

**Comment by suppergerrie2** [comment]
Yeah I should probably change this to a general TODO instead of just upgrades
